name: CI/CD

on:
    push:
      paths:
        - infrastructure/*
        - alpaca/*
      branches:
        - main
    pull_request:
      paths:
        - infrastructure/*
        - alpaca/*
      branches:
        - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PRODUCTION_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRODUCTION_SECRET_KEY }}

jobs:
    terraform-plan-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.9.8"

            - name: Terraform init Production
              working-directory: ./infrastructure
              run: terraform init -upgrade

            - name: Terraform Plan Production
              if: ${{ github.event_name == 'pull_request' }}
              working-directory: ./infrastructure
              run: terraform plan

            - name: Terraform Apply Production
              # if: ${{ github.event_name == 'push' }}
              working-directory: ./infrastructure
              run: terraform apply -auto-approve