---
name: Scheduled Buy

on:
  schedule:
    - cron: '30 15 * * 1-5'
  pull_request:

env:
  ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
  ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}


jobs:
  run-buy-script: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: |
          go mod init alpaca
          go build -o myapp

      - name: Run
        run: ./myapp